# dhcpcd.conf - Nintendo 3DS (CyanogenMod 7.2)
#
# Copied to /system/etc/dhcpcd/dhcpcd.conf.  dhcpcd_wlan0 in init.rc runs
#   /system/bin/dhcpcd -dd -f /system/etc/dhcpcd/dhcpcd.conf wlan0

interface wlan0
option subnet_mask, routers, domain_name_servers
